title: 誤り耐性量子コンピュータのアプリケーション研究開発
list_title: News
timezone: Asia/Tokyo
description: >
  「誤り耐性量子コンピュータのアプリケーション研究開発」プロジェクトの公式ページです。

remote_theme: "jekyll/minima@8106bd4"

markdown: kramdown
kramdown:
  math_engine: mathjax

minima:
  date_format: "%Y-%m-%d"

nav_pages:
  - about.md
  - members.md
  - events.md
  - publications.md
  - archive.md

exclude:
  - AGENTS.md
